# Build Info File
build_info = {
 'ASIC_ID': 'ASIC_Cheops_secure_boot',
 'BRANCH': '//depot/SGP/ProductBranches/RosewoodLC/Gen3',
 'BUILDER_NAME': 'szechek.tan',
 'CHANGELIST': '01138956',
 'EXECUTABLE': 'makepy.bat -m=1 RO08.SDM2QQ:day-25:month-10:year-2016:time-223338:rello-2233:relhi-1025:custrel-SBM3:sataextcustrel-FFFF:custflag-F3_CHEOPSLITEM_1_0_SATA_ROSEWOOD_MULE1:autobuilt-0:changelist-01138956:branch-//depot/SGP/ProductBranches/RosewoodLC/Gen3:gid-00306432:ip-0A1E707A:computername-COL-BB-S02:vddreleasenum-0000000:localfileinfo-000000000000000000000000:pkg-CC4638:localrev-00:custfam-SD:custcfg-M2:pkgtime-223338:pkgyyyymmdd-20161025:pkgsfwhwcfg-B6:partnum-100811416:package-yes',
 'GID': '00306432',
 'PACKAGE': 'CC4638',
 'SIGN_GID': '00306432',
 'SIGN_TYPE': 'INNER_AND_OUTER_SIGN',
 'VERSION': 1.0
}