# Build Info File
build_info = {
 'ASIC_ID': 'ASIC_Cheops_secure_boot',
 'BRANCH': '//depot/SGP/ProductBranches/RosewoodLC/Gen3',
 'BUILDER_NAME': 'szechek.tan',
 'CHANGELIST': '01111305',
 'EXECUTABLE': 'makepy.bat -m=1 RT08.SDM9QQ:day-06:month-09:year-2016:time-025148:rello-0251:relhi-0906:custrel-SDM1:sataextcustrel-FFFF:custflag-F3_CHEOPSLITEM_1_0_SATA_ROSEWOOD_MULE1:autobuilt-0:changelist-01111305:branch-//depot/SGP/ProductBranches/RosewoodLC/Gen3:gid-00306432:ip-0A1E7079:computername-COL-BB-S01:vddreleasenum-0000000:localfileinfo-000000000000000000000000:pkg-CC4618:localrev-00:custfam-SD:custcfg-M9:pkgtime-025148:pkgyyyymmdd-20160906:pkgsfwhwcfg-98:package-yes',
 'GID': '00306432',
 'PACKAGE': 'CC4618',
 'SIGN_GID': '00306432',
 'SIGN_TYPE': 'INNER_AND_OUTER_SIGN',
 'VERSION': 1.0
}