# Build Info File
build_info = {
 'ASIC_ID': 'ASIC_Cheops_secure_boot',
 'BRANCH': '//depot/SGP/ProductBranches/Rosewood7/Gen3A_SBS10',
 'BUILDER_NAME': 'kenny.choo',
 'CHANGELIST': '01040450',
 'EXECUTABLE': 'makepy.bat -m=1 RW08.SDM2QQ:day-04:month-05:year-2016:time-152102:rello-0001:relhi-6994:custrel-SBM3:sataextcustrel-FFFF:custflag-F3_CHEOPSAM_1_0_SATA_ROSEWOOD_MULE1:autobuilt-0:changelist-01040450:branch-//depot/SGP/ProductBranches/Rosewood7/Gen3A_SBS10:gid-00080603:ip-0A1D36AA:computername-SGP-M071445D024:vddreleasenum-0000000:localfileinfo-000000000000000000000000:pkg-AA6994:localrev-00:custfam-SD:custcfg-M2:pkgtime-152102:pkgyyyymmdd-20160504:pkgsfwhwcfg-A7:package-yes',
 'GID': '00080603',
 'PACKAGE': 'AA6994',
 'SIGN_GID': '00080603',
 'SIGN_TYPE': 'INNER_AND_OUTER_SIGN',
 'VERSION': 1.0
}