# Build Info File
build_info = {
 'ASIC_ID': 'ASIC_Cheops_secure_boot',
 'BRANCH': '//depot/F3-trunk',
 'BUILDER_NAME': 'kenny.choo',
 'CHANGELIST': '01072565',
 'EXECUTABLE': 'makepy.bat -m=1 RW08.SDM1QQ:day-28:month-06:year-2016:time-134626:rello-0001:relhi-7777:custrel-SDM1:sataextcustrel-FFFF:custflag-F3_CHEOPSAM_1_0_SATA_ROSEWOOD_MULE1:autobuilt-0:changelist-01072565:branch-//depot/F3-trunk:gid-00080603:ip-0A1D36D9:computername-SGS-U504520D001:vddreleasenum-0000000:localfileinfo-000000000000000000000000:pkg-AA7777:localrev-00:custfam-SD:custcfg-M1:pkgtime-134626:pkgyyyymmdd-20160628:pkgsfwhwcfg-A7:package-yes',
 'GID': '00080603',
 'PACKAGE': 'AA7777',
 'SIGN_GID': '00080603',
 'SIGN_TYPE': 'INNER_AND_OUTER_SIGN',
 'VERSION': 1.0
}